# Measures the post-migration inventory and WRITES docs/worktree-topology.md.
# Every number in the output comes from a measurement taken here.
#
#   .\scripts\wt-inventory.ps1              reuse the cached measurement if present
#   .\scripts\wt-inventory.ps1 -ReMeasure   re-walk every worktree (minutes)
#
# The cache exists because a full byte measurement of 42 worktrees takes minutes and
# the RESULT (which lane is where, which state, how big) does not change between two
# runs minutes apart. -ReMeasure when you want the bytes re-read from disk.
param([switch]$ReMeasure)
$ErrorActionPreference = 'Continue'
$td   = Get-Content 'G:\Temp\wt-topology-current-tmpdir.txt'
$repo = 'C:\Users\Administrador\Desktop\Nova pasta (3)\TESTE\VOD.RIP'
$w    = 'I:\vod-rip-wt\wip\wt-topology'
Set-Location $w

$class = @{}
foreach ($r in (Import-Csv (Join-Path $td 'classify2.csv'))) { $class[$r.leaf] = $r }
$outcome = @{}
foreach ($l in (Get-Content (Join-Path $td 'migration\migration.tsv') | Where-Object { $_ -notmatch '^lane' })) {
  $f = $l -split "`t"; $outcome[$f[0]] = $f[4]
}
$loc = @{}
foreach ($l in (git -C $repo worktree list --porcelain | Select-String '^worktree ')) {
  $p = ($l -replace '^worktree ','').TrimEnd('/'); $loc[(Split-Path $p -Leaf)] = $p
}

$cache = Join-Path $td 'final-inventory.csv'
if ((Test-Path $cache) -and (-not $ReMeasure)) {
  "reusing cached measurement ($cache) - pass -ReMeasure to re-walk the trees"
  $rows = Import-Csv $cache
} else {
  "measuring bytes..."
  $rows = @()
  foreach ($leaf in ($class.Keys | Sort-Object)) {
    $c = $class[$leaf]
    $p = if ($loc.ContainsKey($leaf)) { $loc[$leaf] } else { $null }
    $bytes = 0
    if ($p -and (Test-Path -LiteralPath $p)) {
      $m = Get-ChildItem -LiteralPath $p -Force -Recurse -File -ErrorAction SilentlyContinue |
           Measure-Object -Property Length -Sum
      $bytes = [int64]$m.Sum
    }
    $rows += [pscustomobject]@{
      lane=$leaf; path=$p; branch=$c.branch; merged=$c.merged; ahead=$c.ahead
      dirty=$c.dirty; state=$c.state; junction=($c.junction -eq 'True')
      bytes=$bytes; outcome=$outcome[$leaf]
    }
  }
  $rows | Export-Csv $cache -NoTypeInformation -Encoding UTF8
}

# NOTE: Get-PSDrive takes the drive NAME, with no colon. Passing 'I:' raises
# "Cannot find drive", and $free[$d] silently became 0, so an earlier run wrote
# "C: 0 GB - G: 0 GB - H: 0 GB - I: 0 GB" into the doc. A measurement that fails
# must not be formatted as if it succeeded.
$free = @{}
foreach ($d in 'C','G','H','I') {
  $drv = Get-PSDrive -Name $d -ErrorAction SilentlyContinue
  if ($drv) { $free["$d`:"] = [math]::Round(($drv.Free/1GB),1) } else { $free["$d`:"] = 'unavailable' }
}

# When $rows came from the CSV cache its `bytes` is a STRING, and Measure-Object
# refuses strings ("the input object is not numeric") - so cast before summing.
# An earlier version of this file hit exactly that and the totals silently came out
# empty; a measurement that cannot be computed must not be printed as if it were.
$bytesOf = { param($set) ($set | ForEach-Object { [int64]$_.bytes } | Measure-Object -Sum).Sum }
$totalB = & $bytesOf $rows
$movB   = & $bytesOf ($rows | Where-Object { $_.junction -ne 'True' })
$juncB  = & $bytesOf ($rows | Where-Object { $_.junction -eq 'True' })
$nMoved   = ($rows | Where-Object { $_.outcome -eq 'MOVED' }).Count
$nAlready = ($rows | Where-Object { $_.outcome -eq 'ALREADY' }).Count
$nRefused = ($rows | Where-Object { $_.outcome -eq 'REFUSED-junction' }).Count
$nDone    = ($rows | Where-Object { $_.state -eq 'done' }).Count
$nUnsure  = ($rows | Where-Object { $_.state -eq 'unsure' }).Count
$nWip     = ($rows | Where-Object { $_.state -eq 'wip' }).Count
$nArch    = ($rows | Where-Object { $_.state -eq 'archive' }).Count
$ledgerRows = (Get-Content 'docs/wt-migration-ledger.tsv' | Where-Object { $_ -notmatch '^#' -and $_.Trim() }).Count
$inspected  = (git -C $repo worktree list --porcelain | Select-String '^worktree I:/vod-rip-wt').Count
$strays     = (git -C $repo worktree list --porcelain | Select-String '^worktree I:/TEMP').Count
$mainSha    = (git -C $repo rev-parse --short main)
$now        = (Get-Date).ToString('yyyy-MM-dd HH:mm zzz')

$md = @()
$md += '# Worktree topology'
$md += ''
$md += "Generated by ``scripts/wt-inventory.ps1`` on $now. Every number below is measured, not typed."
$md += 'Do not hand-edit the table; re-run the generator.'
$md += ''
$md += '## Nothing was deleted'
$md += ''
$md += '**No worktree, branch, or file was deleted at any point in this change.** Every'
$md += 'relocation was `git worktree move`, which is reversible by running the same'
$md += 'command backwards. The 10 worktrees that were not moved were not touched at all.'
$md += 'There is no `git worktree remove`, no `git branch -D`, and no `rm -rf` anywhere in'
$md += '`scripts/wt-migrate.sh` or `scripts/wt-restore.sh`.'
$md += ''
$md += '## Layout'
$md += ''
$md += '```'
$md += 'I:/vod-rip-wt/            <- the ONE place a VOD.RIP worktree may be created'
$md += '  wip/                    unmerged branch with real work'
$md += '  unsure/                 merged-or-not but DIRTY, or state not established'
$md += '  done/                   proven merged into main AND a clean tree'
$md += '  archive/                genuinely abandoned, reason recorded'
$md += '```'
$md += ''
$md += 'The four state names are **verified**, not assumed: they come from'
$md += '`wtroot_states` in `scripts/lib/worktree-roots.sh` (ported verbatim from'
$md += '`I:\!manager\scripts\lib\worktree-roots.sh`).'
$md += ''
$md += '### Why `I:` and not `G:` or `H:`'
$md += ''
$md += '`git worktree move` is **same-drive-only**. All 42 registered VOD.RIP worktrees'
$md += 'were on `I:`. A root on `G:` or `H:` would not merely be slower - it would make'
$md += 'the whole migration impossible, because git refuses a cross-drive move outright.'
$md += 'So the root shares `I:` with the trees being moved. `archive/` is a sibling of'
$md += 'the other three states, so it is on the same drive as the root for free, which is'
$md += 'the entire reason that state exists.'
$md += ''
$md += "Free space, measured now: C: $($free['C:']) GB - G: $($free['G:']) GB - H: $($free['H:']) GB - I: $($free['I:']) GB."
$md += ''
$md += '### This moved nothing across drives, so it freed no space'
$md += ''
$md += "**Bytes reclaimed: 0.** The $([math]::Round($totalB/1MB)) MB measured across these lanes"
$md += "($([math]::Round($totalB/1GB,2)) GiB total) sits on exactly the same drive as before. A move"
$md += 'inside one drive is a rename. If the goal is storage, this change is not it:'
$md += 'reclaiming space means moving trees to `H:` (102 GB free), which cannot be done'
$md += 'with `git worktree move` and is therefore a separate, riskier decision.'
$md += ''
$md += '## The three commands'
$md += ''
$md += 'Create a lane (the destination is resolved from the manifest, never typed):'
$md += '```'
$md += 'scripts/wt-new.sh --project vod-rip --lane my-lane            # -> I:/vod-rip-wt/wip/my-lane'
$md += 'scripts/wt-new.sh --project vod-rip --lane my-lane --state done'
$md += '```'
$md += ''
$md += 'Put one lane back exactly where it came from:'
$md += '```'
$md += 'scripts/wt-restore.sh --lane wt-ar        # -> I:/TEMP/wt-ar'
$md += '```'
$md += ''
$md += 'Undo the entire migration (safe to run twice; it converges):'
$md += '```'
$md += 'scripts/wt-restore.sh --all'
$md += '```'
$md += ''
$md += "See what is reversible: ``scripts/wt-restore.sh --list`` (reads"
$md += "`docs/wt-migration-ledger.tsv`, currently $ledgerRows rows)."
$md += ''
$md += 'Run `bash scripts/wt-new.sh --selftest` after touching the tooling: 27 checks, two'
$md += 'arms (a throwaway fixture repo, then read-only assertions against this manifest).'
$md += ''
$md += '## Inventory'
$md += ''
$md += "Classified: **done $nDone, unsure $nUnsure, wip $nWip, archive $nArch** (total $($rows.Count))."
$md += ''
$md += 'Classification rules, applied strictly:'
$md += ''
$md += '- `done` - branch proven merged into `main` (`git branch --merged main` AND'
$md += '  `git log main..<branch>` empty) **and** a clean tree.'
$md += "- ``unsure`` `` - merged or not, but the tree is dirty, or the state could not be"
$md += '  established. A classification that cannot be justified is `unsure`, never `done`.'
$md += '- `wip` - unmerged branch with real work.'
$md += '- `archive` - genuinely abandoned with a recorded reason. **Nothing met this bar.**'
$md += '  Several branches are named `...-parked` (`wt-parkui`, `wtage`), which means'
$md += '  deliberately held open, the opposite of abandoned. Guessing `archive` here would'
$md += '  have been an unproven claim, so those lanes are classified on their actual'
$md += '  merge/clean state instead.'
$md += ''
$md += '| lane | branch | merged | ahead | dirty | bytes | state | moved |'
$md += '|---|---|---|---|---|---|---|---|'
foreach ($r in ($rows | Sort-Object state, lane)) {
  $bytes = '{0:N0}' -f $r.bytes
  $j = if ($r.junction) { ' (junction: NOT moved)' } else { '' }
  $md += "| ``$($r.lane)``$j | ``$($r.branch)`` | $($r.merged) | $($r.ahead) | $($r.dirty) | $bytes | $($r.state) | $($r.outcome) |"
}
$md += ''
$md += '## The 10 lanes that were refused and left in place'
$md += ''
$md += 'Each of these holds a `node_modules` **junction** pointing at the shared main tree'
$md += 'on `C:`. `git worktree remove` has already destroyed a dependency tree in this'
$md += 'project through one, so a junctioned tree is not moved either.'
$md += '`scripts/wt-migrate.sh` refuses them with exit code 3 **before running any git'
$md += 'command**. They are the reason the stray count is $strays and not 0.'
$md += ''
$md += '| lane | state | bytes | junction target |'
$md += '|---|---|---|---|'
foreach ($r in ($rows | Where-Object junction | Sort-Object lane)) {
  $md += "| ``$($r.lane)`` | $($r.state) | $(('{0:N0}' -f $r.bytes)) | shared ``main/node_modules`` on C: |"
}
$md += ''
$md += 'Moving or removing these is an owner decision, not a scripted one. Until then they'
$md += 'stay in `I:/TEMP` and `wt-new.sh` keeps refusing lanes that would collide.'
$md += ''
$md += '## A note on the shared manifest'
$md += ''
$md += 'The shared portfolio manifest `I:\!manager\worktree-roots.tsv` **already had a'
$md += '`vod-rip` row**, declaring `G:/vod-rip-wt`. It is another repo''s file, it is'
$md += 'owned there, and its ceiling (1 stray, measured 2026-09-25) is long stale against'
$md += 'the 42 lanes, so it was **left untouched**. This repo therefore uses its own'
$md += 'manifest, `scripts/worktree-roots.tsv`, which the ported library defaults to.'
$md += ''
$md += 'The consequence, stated plainly: anyone pointing `WORKTREE_ROOTS` at the shared'
$md += 'file gets `G:`, which is not where these lanes live. Reconciling the two is an'
$md += 'owner decision about which root is canonical, recorded here rather than guessed.'
$md += ''
$md += '## Provenance'
$md += ''
$md += '`scripts/wt-new.sh` and `scripts/lib/worktree-roots.sh` are ported from'
$md += '`I:\!manager\scripts\wt-new.sh` and `I:\!manager\scripts\lib\worktree-roots.sh`'
$md += '(upstream not modified). The only functional change to the library is WHERE the'
$md += 'manifest lives; every refusal is unchanged. `wtnew_port_note` in the library'
$md += 'prints the full diff. `scripts/lib/wt-vodrip.sh`, `wt-migrate.sh` and'
$md += '`wt-restore.sh` are new and specific to this repo.'
$md += ''

$md -join "`n" | Set-Content 'docs/worktree-topology.md' -Encoding UTF8
"wrote docs/worktree-topology.md"
"MOVED=$nMoved ALREADY=$nAlready REFUSED=$nRefused | done=$nDone unsure=$nUnsure wip=$nWip archive=$nArch"
"bytes total={0:N0} movable={1:N0} junction={2:N0}" -f $totalB,$movB,$juncB
"ledger_rows=$ledgerRows under_root=$inspected strays_in_TEMP=$strays main=$mainSha"